name = "zola-paper"
description = "A clean theme inspired from hugo-paper."
license = "MIT"
homepage = "https://github.com/schoenenberg/zola-paper"
# The minimum version of Zola required
min_version = "0.11.0"
# An optional live demo URL
demo = "https://schoenenberg.github.io/zola-paper"

title = "Zola-Paper"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
links = []
google_analytics = { enabled = false, id = ""}

# The theme author info: you!
[author]
name = "Maximilian Schoenenberg"
homepage = "https://schoenenberg.dev"

[original]
author =  "nanxiaobei"
homepage = "https://nanxiaobei.github.io/hugo-paper/"
repo = "https://github.com/nanxiaobei/hugo-paper/"
